2022-04-20 21:58:02,348 [DEBUG] errors: Example error
2022-04-20 21:58:55,714 [DEBUG] errors: Example debug
2022-04-20 22:02:19,097 [DEBUG] errors: Example debug
2022-04-20 22:02:19,098 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 54, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-20 22:03:58,554 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 54, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-20 22:21:05,449 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 54, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-20 22:21:05,648 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 54, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-20 22:21:05,892 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 54, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-20 22:21:06,064 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 54, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-20 22:21:06,227 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 54, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-20 22:21:06,393 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 54, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-20 22:21:06,536 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 54, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-20 22:21:06,728 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 54, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-20 22:21:06,874 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 54, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-20 22:21:07,027 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 54, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-20 22:23:54,954 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 54, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-20 22:23:55,255 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 54, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-20 22:23:55,631 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 54, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-20 22:23:55,889 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 54, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-20 22:23:56,127 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 54, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-20 22:23:56,324 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 54, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-20 22:23:56,568 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 54, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-20 22:23:56,740 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 54, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-20 22:23:56,911 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 54, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-20 22:23:57,061 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 54, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-20 22:24:21,855 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 54, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-20 22:24:22,014 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 54, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-20 22:24:22,219 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 54, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-20 22:24:22,362 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 54, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-20 22:24:22,503 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 54, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-20 22:24:22,680 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 54, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-20 22:24:22,834 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 54, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-20 22:24:22,984 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 54, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-20 22:24:23,122 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 54, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-20 22:24:23,272 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 54, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-21 01:03:04,421 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 54, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-21 01:03:04,613 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 54, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-21 01:03:04,898 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 54, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-21 01:03:05,096 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 54, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-21 01:03:05,288 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 54, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-21 01:03:05,473 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 54, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-21 01:03:05,680 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 54, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-21 01:03:05,862 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 54, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-21 01:03:06,075 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 54, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-21 01:03:06,278 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 54, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-21 01:08:25,906 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 54, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-21 01:08:26,056 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 54, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-21 01:08:26,255 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 54, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-21 01:08:26,424 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 54, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-21 01:08:26,597 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 54, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-21 01:08:26,750 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 54, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-21 01:08:26,898 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 54, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-21 01:08:27,058 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 54, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-21 01:08:27,197 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 54, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-21 01:08:27,339 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 54, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-21 01:21:24,196 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 52, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-21 01:21:24,464 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 52, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-21 01:21:24,820 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 52, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-21 01:21:25,102 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 52, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-21 01:21:25,298 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 52, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-21 01:21:25,504 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 52, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-21 01:21:25,669 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 52, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-21 01:21:25,847 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 52, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-21 01:21:26,006 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 52, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-21 01:21:26,147 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 52, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-21 01:25:09,779 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 51, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-21 01:41:15,135 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 51, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-21 14:09:09,921 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 51, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-21 14:09:10,067 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 51, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-21 14:09:10,252 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 51, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-21 14:09:10,395 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 51, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-21 14:09:10,537 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 51, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-21 14:09:10,686 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 51, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-21 14:09:10,832 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 51, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-21 14:09:10,973 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 51, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-21 14:09:11,112 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 51, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-21 14:09:11,252 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 51, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-21 14:09:18,904 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 51, in configure_logging
    1/0
ZeroDivisionError: division by zero
2022-04-21 14:22:23,270 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 53, in configure_logging
    1 / 0
ZeroDivisionError: division by zero
2022-04-21 14:22:23,418 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 53, in configure_logging
    1 / 0
ZeroDivisionError: division by zero
2022-04-21 14:22:23,600 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 53, in configure_logging
    1 / 0
ZeroDivisionError: division by zero
2022-04-21 14:22:23,737 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 53, in configure_logging
    1 / 0
ZeroDivisionError: division by zero
2022-04-21 14:22:23,875 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 53, in configure_logging
    1 / 0
ZeroDivisionError: division by zero
2022-04-21 14:22:24,020 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 53, in configure_logging
    1 / 0
ZeroDivisionError: division by zero
2022-04-21 14:22:24,160 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 53, in configure_logging
    1 / 0
ZeroDivisionError: division by zero
2022-04-21 14:22:24,299 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 53, in configure_logging
    1 / 0
ZeroDivisionError: division by zero
2022-04-21 14:22:24,433 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 53, in configure_logging
    1 / 0
ZeroDivisionError: division by zero
2022-04-21 14:22:24,570 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 53, in configure_logging
    1 / 0
ZeroDivisionError: division by zero
2022-04-21 14:23:36,961 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 53, in configure_logging
    1 / 0
ZeroDivisionError: division by zero
2022-04-21 14:28:44,372 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 55, in configure_logging
    1 / 0
ZeroDivisionError: division by zero
2022-04-21 14:28:58,465 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 55, in configure_logging
    1 / 0
ZeroDivisionError: division by zero
2022-04-21 14:28:58,617 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 55, in configure_logging
    1 / 0
ZeroDivisionError: division by zero
2022-04-21 14:28:58,801 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 55, in configure_logging
    1 / 0
ZeroDivisionError: division by zero
2022-04-21 14:28:58,941 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 55, in configure_logging
    1 / 0
ZeroDivisionError: division by zero
2022-04-21 14:28:59,082 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 55, in configure_logging
    1 / 0
ZeroDivisionError: division by zero
2022-04-21 14:28:59,227 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 55, in configure_logging
    1 / 0
ZeroDivisionError: division by zero
2022-04-21 14:28:59,362 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 55, in configure_logging
    1 / 0
ZeroDivisionError: division by zero
2022-04-21 14:28:59,501 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 55, in configure_logging
    1 / 0
ZeroDivisionError: division by zero
2022-04-21 14:28:59,642 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 55, in configure_logging
    1 / 0
ZeroDivisionError: division by zero
2022-04-21 14:28:59,782 [ERROR] errors: Hello this is an error
Traceback (most recent call last):
  File "/home/myuser/app/logging_config/__init__.py", line 55, in configure_logging
    1 / 0
ZeroDivisionError: division by zero
